export const TEST_REDUX = 'TEST_REDUX';
export const CREATE_REDUX = 'CREATE_REDUX';
export const READ_REDUX = 'READ_REDUX';
export const UPDATE_REDUX = 'UPDATE_REDUX';
export const DELETE_REDUX = 'DELETE_REDUX';
export const POST_DATA_API_SUCCESS = 'POST_DATA_API_SUCCESS';
export const POST_DATA_API_FAIL = 'POST_DATA_API_FAIL';
export const SHOW_LOADING="GLOBAL_SHOW_LOADING";
export const HIDE_LOADING="GLOBAL_HIDE_LOADING";

